### ISSUE TITLE
0.3.5.8 does not run

### ISSUE THREAD

**Issue by cghislai** [svengo/docker-tor#4]
I have errors running the latest version:
Error loading shared library libssl.so.45: No such file or directory (needed by /usr/bin/tor)
Error loading shared library libcrypto.so.43: No such file or directory (needed by /usr/bin/tor)
Error relocating /usr/bin/tor: ENGINE_get_default_ECDSA: symbol not found
Error relocating /usr/bin/tor: SSL_export_keying_material: symbol not found

**Comment by svengo** [comment]
Added libressl package. I don't know why, but until yesterday it wasn't needed.
